# Mad lib program cuz i was told to

def mad_lib():
    print("Give me 6 nouns")
    noun1 = input("Noun 1: ")
    noun2 = input("Noun 2: ")
    noun3 = input("Noun 3: ")
    noun4 = input("Noun 4: ")
    noun5 = input("Noun 5: ")
    noun6 = input("Noun 6: ")
    print()
    print("Now give me 4 adjectives")
    adj1 = input("Adjective 1: ")
    adj2 = input("Adjective 2: ")
    adj3 = input("Adjective 3: ")
    adj4 = input("Adjective 4: ")
    print()
    print("Now give me 2 verbs")
    verb1 = input("Verb 1: ")
    verb2 = input("Verb 2: ")
    print()
    print("Now give me 1 adverb")
    adverb1 = input("Adverb 1: ")
    print()
    print("Now give me 1 emotion")
    emotion1 = input("Emotion 1: ")
    print()
    print("Here is your mad lib:")
    print()
    return(f"Today I went to the {noun1}. I saw a {adj1} {noun2} jumping up and down in a puddle of {noun3}. It {adverb1} {verb1} through the large tunnel that led to its {adj2} {noun4}. I got some peanuts and passed them through the cage to a gigantic gray {noun5} towering above my head. Feeding that animal made me hungry. I went to get a {adj3} scoop of ice cream. It filled my stomach. Afterwards I had to {verb2} {emotion1} to catch our bus. When I got home I {adverb1} {verb1} my mom for a {adj4} day at the zoo.")

print(mad_lib())